version: '3'

x-go-app-options: &go-app-options
  build:
    context: .
    dockerfile: Dockerfile
    target: prod
  # volumes:
    # - .:/app
  # environment:
  #   - ENV=development
  depends_on:
    - db
  # restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: "2.0"
        memory: "4G"
      reservations:
        cpus: "0.25"
        memory: "512M"

services:
  go-fr:
    <<: *go-app-options
    ports:
    - "8080:8000"
    command: /app/go-fr
    environment:
    - LOG_LEVEL=FATAL

  go-bun:
    <<: *go-app-options
    ports:
    - "8081:8000"
    command: /app/go-bun

  go-echo:
    <<: *go-app-options
    ports:
    - "8082:8000"
    command: /app/go-echo
  go-fuego:
    <<: *go-app-options
    ports:
    - "8083:8000"
    command: /app/go-fuego
  go-fiber:
    <<: *go-app-options
    ports:
    - "8084:8000"
    command: /app/go-fiber
  go-std:
    <<: *go-app-options
    ports:
    - "8085:8000"
    command: /app/go-std
  go-gin:
    <<: *go-app-options
    ports:
    - "8086:8000"
    command: /app/go-gin
    environment:
    - GIN_MODE=release
  go-gorilla-mux:
    <<: *go-app-options
    ports:
    - "8087:8000"
    command: /app/go-gorilla-mux
  go-chi:
    <<: *go-app-options
    ports:
    - "8088:8000"
    command: /app/go-chi
  go-hertz:
    <<: *go-app-options
    ports:
    - "8089:8000"
    command: /app/go-hertz
  go-std-env-test-off:
    <<: *go-app-options
    ports:
    - "8090:8000"
    command: /app/go-std
    environment:
      - GOGC=off # This consumes a lot of memory
      - GOMAXPROCS=2
      - GOMEMLIMIT=4GiB
  go-std-env-test-on:
    <<: *go-app-options
    ports:
    - "8091:8000"
    command: /app/go-std
    environment:
      - GOGC=75
      - GOMAXPROCS=2
      - GOMEMLIMIT=4GiB
  go-std-env-test-auto:
    <<: *go-app-options
    ports:
    - "8093:8000"
    command: /app/go-std-auto-perf
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db-data:
