# https://taskfile.dev

version: '3'


tasks:
  go-becnhmark:
    cmds:
      - go test -bench=. -benchtime=10s -count=5 ./testing/...
    silent: true

  becnhmark:
    cmds:
    - go run cmd/bench/generate/main.go
    - task: results
  results:
    cmds:
    - echo "============================================="
    - echo "Printing results"
    - echo "============================================="
    - go run cmd/bench/results/main.go
    silent: true