# https://taskfile.dev

version: '3'


tasks:
  go-becnhmark:
    cmds:
      - go test -bench=. -benchtime=10s -count=5 ./testing/...
    silent: true

  becnhmark:
    # vars:
    #   OUTPUTFILE: "out.txt"
    cmds:
    - go run cmd/bench/generate/main.go
    # - echo "" > {{.OUTPUTFILE}}
    # - "echo \"\nName: go-fr\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8080 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-bun\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8081 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-echo\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8082 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-fuego\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8083 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-fiber\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8084 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-std\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8085 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-gin\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8086 >> {{.OUTPUTFILE}}"
    # - "echo \"\nName: go-gorilla-mux\" >> {{.OUTPUTFILE}} && oha -j --no-tui -n 100 -c 100 -p 100 -z 30s http://localhost:8087 >> {{.OUTPUTFILE}}"
    - task: results
  results:
    cmds:
    - echo "============================================="
    - echo "Printing results"
    - echo "============================================="
    - go run cmd/bench/results/main.go
    silent: true